# version format
version: 2.4.5-{build}

# pull request template
pull_requests:
  do_not_increment_build_number: true

# vm template
image: Visual Studio 2022

# msbuild configuration
configuration:
- Debug

# build step
build_script:
  - cmd: dotnet restore
  - cmd: dotnet build Test\Test.csproj --framework net48
  - cmd: dotnet publish Test\Test.csproj --framework net6.0 --runtime win-x86 --self-contained true -p:PublishSingleFile=true
  - cmd: dotnet publish Test\Test.csproj --framework net6.0 --runtime win-x64 --self-contained true -p:PublishSingleFile=true
  - cmd: dotnet publish Test\Test.csproj --framework net6.0 --runtime linux-x64 --self-contained true -p:PublishSingleFile=true
  - cmd: dotnet publish Test\Test.csproj --framework net6.0 --runtime osx-x64 --self-contained true -p:PublishSingleFile=true
  - cmd: dotnet pack HLLibSharp\HLLibSharp.csproj --output %APPVEYOR_BUILD_FOLDER%

# post-build script
after_build:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Test\bin\Debug\net48
  - cmd: 7z a -tzip %APPVEYOR_BUILD_FOLDER%\HLLibSharp_net48.zip *
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Test\bin\Debug\net6.0\win-x86\publish\
  - cmd: 7z a -tzip %APPVEYOR_BUILD_FOLDER%\HLLibSharp_net6.0_win-x86.zip *
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Test\bin\Debug\net6.0\win-x64\publish\
  - cmd: 7z a -tzip %APPVEYOR_BUILD_FOLDER%\HLLibSharp_net6.0_win-x64.zip *
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Test\bin\Debug\net6.0\linux-x64\publish\
  - cmd: 7z a -tzip %APPVEYOR_BUILD_FOLDER%\HLLibSharp_net6.0_linux-x64.zip *
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Test\bin\Debug\net6.0\osx-x64\publish\
  - cmd: 7z a -tzip %APPVEYOR_BUILD_FOLDER%\HLLibSharp_net6.0_osx-x64.zip *

# success/failure tracking
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL

# artifact linking
artifacts:
- path: HLLibSharp_net48.zip
  name: HLLibSharp (.NET Framework 4.8)
- path: HLLibSharp_net6.0_win-x86.zip
  name: HLLibSharp (.NET 6.0, Windows x86)
- path: HLLibSharp_net6.0_win-x64.zip
  name: HLLibSharp (.NET 6.0, Windows x64)
- path: HLLibSharp_net6.0_linux-x64.zip
  name: HLLibSharp (.NET 6.0, Linux x64)
- path: HLLibSharp_net6.0_osx-x64.zip
  name: HLLibSharp (.NET 6.0, OSX x64)
- path: '*.nupkg'
  name: Nuget Packages